// 100-prompt benchmark corpus for trading sentiment classification.
// Distribution: 30 clearly bullish, 30 clearly bearish, 20 neutral/factual,
// 20 ambiguous. Ambiguous prompts force the router to escalate, which is
// where the routing logic earns or loses cost vs naive Sonnet-always.

export interface CorpusItem {
  text: string;
  expected: 'bullish' | 'bearish' | 'neutral' | 'ambiguous';
}

export const CORPUS: CorpusItem[] = [
  // --- Clearly bullish (30) ---
  { text: 'BTC just broke 100k resistance with strong volume confirming.', expected: 'bullish' },
  { text: 'ETH printing higher highs on the daily, MACD crossing up.', expected: 'bullish' },
  { text: 'SPY breaking out to all-time highs, breadth indicators flashing green.', expected: 'bullish' },
  { text: 'NVDA gapped up on earnings beat, guidance raised significantly.', expected: 'bullish' },
  { text: 'Gold consolidating above 2100 after the Fed pivot, looks ready to run.', expected: 'bullish' },
  { text: 'Treasury yields rolling over, growth stocks ripping on the news.', expected: 'bullish' },
  { text: 'AAPL reclaimed the 200 SMA on heavy volume, looking constructive.', expected: 'bullish' },
  { text: 'Crude back above the 50 EMA, OPEC cuts holding firm.', expected: 'bullish' },
  { text: 'TSLA delivery numbers crushed estimates, premarket up 8%.', expected: 'bullish' },
  { text: 'Russell 2000 leading the tape, small caps showing relative strength.', expected: 'bullish' },
  { text: 'BTC dominance falling while alts rally, classic risk-on signal.', expected: 'bullish' },
  { text: 'Semiconductor index breaking out of a six-month base.', expected: 'bullish' },
  { text: 'Dollar weakness across the board, commodities catching a bid.', expected: 'bullish' },
  { text: 'AMZN reclaimed prior cycle high, AWS growth reaccelerating.', expected: 'bullish' },
  { text: 'Solana ecosystem TVL hit a new all-time high this week.', expected: 'bullish' },
  { text: 'COIN beating expectations on every line item, raising forward guidance.', expected: 'bullish' },
  { text: 'Bond market pricing in three cuts, equities celebrating the dovish shift.', expected: 'bullish' },
  { text: 'GOOGL bouncing off the 50 DMA with rising relative strength.', expected: 'bullish' },
  { text: 'XLK leading sectors year to date, momentum still building.', expected: 'bullish' },
  { text: 'Bitcoin ETF inflows hit record highs three sessions in a row.', expected: 'bullish' },
  { text: 'Copper ripping on China stimulus headlines, FCX following.', expected: 'bullish' },
  { text: 'Microsoft AI revenue inflecting, investors pricing in a multi-year cycle.', expected: 'bullish' },
  { text: 'Japan reflation trade working, Topix breaking out to multi-decade highs.', expected: 'bullish' },
  { text: 'Goldman raised target to 6500 on stronger earnings outlook.', expected: 'bullish' },
  { text: 'META trading at fresh ATH on strong ad pricing recovery.', expected: 'bullish' },
  { text: 'Solana up 20% this week on memecoin volume and ETF speculation.', expected: 'bullish' },
  { text: 'Crypto fear and greed index hit extreme greed for first time in months.', expected: 'bullish' },
  { text: 'Inflation print cooler than expected, bonds and stocks both rallying.', expected: 'bullish' },
  { text: 'PLTR contract wins flowing in, government deals stacking up.', expected: 'bullish' },
  { text: 'AVGO doubled its dividend, free cash flow trajectory looking solid.', expected: 'bullish' },

  // --- Clearly bearish (30) ---
  { text: 'BTC lost 95k support on heavy volume, next major level is 88k.', expected: 'bearish' },
  { text: 'SPY breaking down through the 200 SMA, volume confirming the move.', expected: 'bearish' },
  { text: 'Yield curve dis-inverting violently, classic recession signal.', expected: 'bearish' },
  { text: 'NVDA gapped down on weak guidance, AI capex story under question.', expected: 'bearish' },
  { text: 'Crude tanked 5% on demand fears out of China.', expected: 'bearish' },
  { text: 'High-yield credit spreads blowing out for the third week running.', expected: 'bearish' },
  { text: 'AAPL lost the rising trendline, China revenue weakness accelerating.', expected: 'bearish' },
  { text: 'TSLA missed deliveries badly, stock down 12% premarket.', expected: 'bearish' },
  { text: 'BTC dominance spiking while alts collapse, risk-off rotation.', expected: 'bearish' },
  { text: 'Dollar ripping higher, EM currencies under serious pressure.', expected: 'bearish' },
  { text: 'VIX above 25 with the term structure inverting, hedges getting bid.', expected: 'bearish' },
  { text: 'Semis broke down through key support, sector rotation out clearly.', expected: 'bearish' },
  { text: 'XLF leading lower, regional bank stress reappearing.', expected: 'bearish' },
  { text: 'GLD breaking below 50 DMA, real yields surging.', expected: 'bearish' },
  { text: 'Solana network congestion driving users to alternatives, fees collapsing.', expected: 'bearish' },
  { text: 'COIN trading volume cratered for the third straight quarter.', expected: 'bearish' },
  { text: 'Russell 2000 making lower lows while large caps stall.', expected: 'bearish' },
  { text: 'AMD lost the 200 DMA, momentum traders unwinding.', expected: 'bearish' },
  { text: 'CPI print hot, bonds and equities both selling off hard.', expected: 'bearish' },
  { text: 'GOOGL antitrust ruling against them, ad business at risk.', expected: 'bearish' },
  { text: 'Crypto leverage flushed, $300m liquidations in 4 hours.', expected: 'bearish' },
  { text: 'Hedge fund net exposure at decade highs, contrarian signal flashing.', expected: 'bearish' },
  { text: 'META capex guide blew through expectations, margins compressing.', expected: 'bearish' },
  { text: 'JPM warning on consumer credit losses, charge-offs trending higher.', expected: 'bearish' },
  { text: 'Oil dropping 4% on inventory build, transports following lower.', expected: 'bearish' },
  { text: 'PLTR insider selling accelerating, lockup expiry looming.', expected: 'bearish' },
  { text: 'NFLX subscriber growth missed, ad tier monetization disappointing.', expected: 'bearish' },
  { text: 'Bitcoin futures basis collapsing, structural demand weakening.', expected: 'bearish' },
  { text: 'AVGO guidance below consensus, AI chip cycle showing first cracks.', expected: 'bearish' },
  { text: 'Asia markets opening sharply lower on China property stress.', expected: 'bearish' },

  // --- Neutral / factual (20) ---
  { text: 'BTC trading sideways between 95k and 100k for the past two weeks.', expected: 'neutral' },
  { text: 'Fed minutes released today at 2pm ET, no major surprises expected.', expected: 'neutral' },
  { text: 'NVDA earnings scheduled for after the close on Wednesday.', expected: 'neutral' },
  { text: 'CPI print due tomorrow morning, consensus is 3.2% headline.', expected: 'neutral' },
  { text: 'Crude inventory report came in line with expectations.', expected: 'neutral' },
  { text: 'SPY closed unchanged on the day, volume below average.', expected: 'neutral' },
  { text: 'AAPL holding the 50 DMA, consolidating in a tight range.', expected: 'neutral' },
  { text: 'Bond auction results were in line with the when-issued levels.', expected: 'neutral' },
  { text: 'Crypto market cap holding $3.8T, no major moves overnight.', expected: 'neutral' },
  { text: 'GDP revision came in at 2.4%, unchanged from prior estimate.', expected: 'neutral' },
  { text: 'OPEC meeting next week, current production targets expected to hold.', expected: 'neutral' },
  { text: 'TSLA delivery window opens next month, estimates between 480k and 510k.', expected: 'neutral' },
  { text: 'ETH staking ratio holding near 28% of supply.', expected: 'neutral' },
  { text: 'Dollar index trading at 104, range-bound for the past month.', expected: 'neutral' },
  { text: 'BLS jobs report out Friday, consensus 175k nonfarm payrolls.', expected: 'neutral' },
  { text: 'COIN reporting earnings next Tuesday, no preannouncement issued.', expected: 'neutral' },
  { text: 'Gold trading at 2050, holding the 200 DMA on the daily.', expected: 'neutral' },
  { text: 'Semis index closed flat, breadth roughly even.', expected: 'neutral' },
  { text: 'Solana validator count at 1850, slot times normal.', expected: 'neutral' },
  { text: 'VIX closed at 13.5, near the lower end of the recent range.', expected: 'neutral' },

  // --- Ambiguous / mixed signals (20) — these should drive escalation ---
  { text: 'BTC pumped on the news but volume looks weak, divergence on RSI.', expected: 'ambiguous' },
  { text: 'NVDA beat earnings but guidance was soft, stock down despite the beat.', expected: 'ambiguous' },
  { text: 'Fed cut 25bps but Powell sounded hawkish on the path forward.', expected: 'ambiguous' },
  { text: 'SPY hit a new high but breadth deteriorating under the surface.', expected: 'ambiguous' },
  { text: 'Strong jobs print but wage growth cooling, mixed read for the Fed.', expected: 'ambiguous' },
  { text: 'TSLA deliveries beat but margins compressed for the fourth quarter running.', expected: 'ambiguous' },
  { text: 'AAPL services growth strong but iPhone units declining year over year.', expected: 'ambiguous' },
  { text: 'Crypto rallied on ETF inflows but funding rates already extreme.', expected: 'ambiguous' },
  { text: 'Crude bouncing on inventory draw but demand outlook still weak.', expected: 'ambiguous' },
  { text: 'META ad pricing recovering but Reality Labs losses widening.', expected: 'ambiguous' },
  { text: 'Bond yields fell but on flight-to-safety not on dovish data.', expected: 'ambiguous' },
  { text: 'GOOGL cloud beat but search revenue showing first signs of pressure.', expected: 'ambiguous' },
  { text: 'BTC breaking out but on-chain flows show whales distributing.', expected: 'ambiguous' },
  { text: 'CPI cooled but core services inflation sticky, mixed message.', expected: 'ambiguous' },
  { text: 'AMD AI revenue accelerating but PC segment dragging overall growth.', expected: 'ambiguous' },
  { text: 'Solana TVL rising but most activity is concentrated in one protocol.', expected: 'ambiguous' },
  { text: 'JPM beat consensus but loan loss provisions stepped up materially.', expected: 'ambiguous' },
  { text: 'COIN revenue beat but staking revenue falling on lower SOL prices.', expected: 'ambiguous' },
  { text: 'Gold making new highs but real yields rising in tandem.', expected: 'ambiguous' },
  { text: 'PLTR contract wins strong but commercial growth decelerating.', expected: 'ambiguous' },
];

if (CORPUS.length !== 100) {
  throw new Error(`Corpus must be exactly 100 items, got ${CORPUS.length}`);
}
